Project/Project.MVC/Models/ErrorViewModel.cs
namespace Project.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project/Project.MVC/Models/PageResult.cs
using Project.Service.Models;

namespace Project.MVC.Models
{
	public class PageResult<T> where T : class 
	{
		public PageResult(string filter,
        int page,
        int pageSize,
        SortOrder sortOrder,
		SortBy sortBy)
		{
			Query = new QueryParameters(filter, page, pageSize, sortOrder, sortBy);
		}
		public List<T> Data { get; set; } 
		public QueryParameters Query { get; set; }
	}
}

Project/Project.MVC/Controllers/VehicleMakeController.cs
using Microsoft.AspNetCore.Mvc;
using Ninject;
using Project.MVC.Models;
using Project.Service;
using Project.Service.Models;
using System.Diagnostics;
using System.Text.Json;

namespace Project.MVC.Controllers
{

    public class VehicleMakeController : Controller
    {
        private readonly IVehicleMakeService _service;
        private readonly IVehicleModelService _modelService;

        public VehicleMakeController(IVehicleMakeService makeService,
            IVehicleModelService modelService)
        {
            _service = makeService;
            _modelService = modelService;
        }

        [HttpGet]
        public IActionResult Index( string filter,
            int page = 1,
            int pageSize = 10,
            SortOrder sortOrder = SortOrder.Ascending,
            SortBy sortBy = SortBy.Name)
        {
            if (string.IsNullOrWhiteSpace(filter)) 
            {
                filter = string.Empty;
            }
            var pagedResult = new PageResult<VehicleMakeDTO>(filter, page, pageSize, sortOrder, sortBy);
            var vehicleMakes = _service.GetAllVehicleMakes(pagedResult.Query);
            pagedResult.Data = vehicleMakes;
            return View(pagedResult);
        }

        [HttpGet]
        public async Task<IActionResult> GetVehicleMake([FromQuery] Guid id)
        {
            var vehicleMake = await _service.GetVehicleMakeAsync(id);
            if (vehicleMake is null)
            {
                return StatusCode(204);
            }
            return View(vehicleMake);
        }

        [HttpPost]
        public async Task<IActionResult> CreateVehicleMake( VehicleMakeDTO make)
        {

            var vehicleMake = await _service.CreateVehicleMakeAsync(make);
            if (vehicleMake == false)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult CreateVehicleMake()
        {

            var vehicleMake = new VehicleMakeDTO();
            return View(vehicleMake);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateVehicleMake(Guid id)
        {
            var vehicleMake = await _service.GetVehicleMakeAsync(id);

            if (vehicleMake is null)
            {
                return StatusCode(204);
            }
            return View(vehicleMake);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateVehicleMake(VehicleMakeDTO make)
        {
            var isUpdated = await _service.UpdateVehicleMakeAsync(make);
            if (!isUpdated)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }
        

        [HttpGet]
        public async Task<IActionResult> DeleteVehicleMake( Guid id)
        {

            var isDeleted = await _service.DeleteVehicleMakeAsync(id);
            if (!isDeleted)
            {
                return StatusCode(204);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Project/Project.MVC/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project.MVC.Models;
using Project.Service;
using Project.Service.Models;

namespace Project.MVC.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _service;

        public VehicleModelController( IVehicleModelService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index(string filter,
            int page = 1,
            int pageSize = 10,
            SortOrder sortOrder = SortOrder.Ascending,
            SortBy sortBy = SortBy.Name)
        {
            if (string.IsNullOrWhiteSpace(filter))
            {
                filter = string.Empty;
            }
            var pagedResult = new PageResult<VehicleModelDTO>(filter, page, pageSize, sortOrder, sortBy);
            var vehicleModels = _service.GetAllVehicleModels(pagedResult.Query);
            pagedResult.Data = vehicleModels;

            return View(pagedResult);
        }


        [HttpGet]
        public async Task<IActionResult> GetVehicleModel( Guid id)
        {
            var vehicleModel = await _service.GetVehicleModelAsync(id);
            if (vehicleModel is null)
            {
                return StatusCode(204);
            }
            return View(vehicleModel);
        }

        [HttpGet]
        public IActionResult CreateVehicleModel(Guid id)
        {

            var vehicleModel = new VehicleModelDTO() { VehicleMakeId = id};
            return View(vehicleModel);
        }
        [HttpPost]

        public async Task<IActionResult> CreateVehicleModel( VehicleModelDTO model)
        {
            model.Id = Guid.Empty;
            var vehicleModel = await _service.CreateVehicleModelAsync(model);
            if (vehicleModel == false)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateVehicleModel(Guid id)
        {
            var vehicleModel = await _service.GetVehicleModelAsync(id);

            if (vehicleModel is null)
            {
                return StatusCode(204);
            }
            return View(vehicleModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateVehicleModel( VehicleModelDTO model)
        {
            var isUpdated = await _service.UpdateVehicleModelAsync(model);
            if (!isUpdated)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> DeleteVehicleModel( Guid id)
        {

            var isDeleted = await _service.DeleteVehicleModelAsync(id);
            if (!isDeleted )
            {
                return StatusCode(204);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Project/Project.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="Index">Vehicle Make</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleModel" asp-action="Index">Vehicle Model</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Project.MVC  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project/Project.MVC/Views/VehicleMake/CreateVehicleMake.cshtml
@using Project.Service.Models

@model VehicleMakeDTO

<head>
	<title>Create Vehicle Make</title>
</head>
<body>
	<form asp-action="CreateVehicleMake">

		<div class="form-group">
			<label asp-for="Name">Name:</label>
			<input asp-for="Name" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Abrv">Abrevation:</label>
			<input asp-for="Abrv" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<input type="submit" value="Add" class="btn"/>
		</div>

	</form>
	<div>
		<a class="nav-link text-dark" asp-controller="VehicleMake" asp-action="Index">Back to list</a>
	</div>
</body>

Project/Project.MVC/Views/VehicleMake/Index.cshtml
@using Project.Service.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PageResult<VehicleMakeDTO>
@{
	var vehicleMakes = Model.Data;
	var query = Model.Query;
}
<div class="row">
	<h1>Vehicle Make</h1>
	<div>
		<button class="btn btn-primary" style="float:right">
			<a asp-action="CreateVehicleMake" style="color:white">
				Add Vehicle Make
			</a>
		</button>
	</div>
</div>

<div class="row">
	@using (Html.BeginForm("Index", "VehicleMake", FormMethod.Get))
	{
		@Html.TextBox("filter")

		<input type="submit" value="Search" />
	}
</div>
<div class="row">
	<table class="arrowes-table table-striped">
		<thead>
			<tr>
				<th>Id</th>
				<th>
					@{
						var sortOrderName = Equals(query.SortOrder, SortOrder.Ascending) ? SortOrder.Descending : SortOrder.Ascending;
					}
					@Html.ActionLink("Name", "Index", new { filter = query.Filter, page = query.Page, pageSize = query.PageSize, sortOrder = sortOrderName, sortBy = SortBy.Name }, new { @class = "text-dark" })
				</th>
				<th justify-content: center>
					@{
						var sortOrderAbrv = Equals(query.SortOrder, SortOrder.Ascending) ? SortOrder.Descending : SortOrder.Ascending;
					}
					@Html.ActionLink("Abrv", "Index", new { filter = query.Filter, page = query.Page, pageSize = query.PageSize, sortOrder = sortOrderAbrv, sortBy = SortBy.Abrv }, new { @class = "text-dark" })
				</th>
				<th></th>
				<th></th>
			</tr>
		</thead>


		<tbody>
			@foreach (var vehicleMake in vehicleMakes)
			{
				<tr>
					<td>@vehicleMake.Id</td>
					<td>@vehicleMake.Name</td>
					<td>
						@vehicleMake.Abrv
					</td>
					<td>
						<a>
							@Html.ActionLink("Edit", "UpdateVehicleMake", new { id=vehicleMake.Id},new {@class="text-dark"})
						</a>
					</td>
					<td>
						<a class="text-dark" asp-controller="VehicleModel" asp-action="CreateVehicleModel" asp-route-id="@vehicleMake.Id">Add Model</a>
					</td>
					<td>
						<a>
							@Html.ActionLink("Delete", "DeleteVehicleMake", new { id=vehicleMake.Id},new {@class="text-dark"})
						</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<div class="row">
	@{
		if (query.Page > 1)
		{
			<div class="col" style="text-align: left">
				<a>
					@Html.ActionLink($"{query.Page - 1}", "Index", new { filter=query.Filter, page = query.Page - 1, pageSize = query.PageSize, sortOrder = query.SortOrder, sortBy = query.SortBy},new {@class="text-dark"})
				</a>
			</div>
		}
	}
	<div class="col" style="text-align: left"  >
		<a>
			@Html.ActionLink($"{query.Page}", "Index", new { filter=query.Filter, page = query.Page, pageSize = query.PageSize, sortOrder = query.SortOrder,sortBy = query.SortBy})
		</a>
	</div>

	@{
	if (vehicleMakes.Count() == query.PageSize)
	{
		<div class="col" style="text-align: left">
			<a>
				@Html.ActionLink($"{query.Page + 1}", "Index", new { filter=query.Filter, page = query.Page + 1, pageSize = query.PageSize, sortOrder = query.SortOrder, sortBy = query.SortBy},new {@class="text-dark"})
			</a>
		</div>
	}

	}
</div>


<script>
	function getSearchValue() { return document.getElementById("searchbox") }
</script>

Project/Project.MVC/Views/VehicleMake/UpdateVehicleMake.cshtml
@using Project.Service.Models

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VehicleMakeDTO
<head>
	<title>Update Vehicle Make</title>
</head>
<body>
	<form asp-action="UpdateVehicleMake">
		<div class="form-group">
			<input asp-for="Id" required />
		</div>
		<div class="form-group">
			<label asp-for="Name">Name:</label>
			<input asp-for="Name" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Abrv">Abrevation:</label>
			<input asp-for="Abrv" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<input type="submit" value="Add" class="btn" />
		</div>

	</form>
	<div>
		<a class="nav-link text-dark" asp-controller="VehicleMake" asp-action="Index">Back to list</a>
	</div>
</body>

Project/Project.MVC/Views/VehicleModel/CreateVehicleModel.cshtml
@using Project.Service.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VehicleModelDTO

<head>
	<title>Create Vehicle Model</title>
</head>
<body>
	<form asp-action="CreateVehicleModel">
		<div class="form-group" hidden>
			<input asp-for="Id"  />
		</div>
		<div class="form-group">
			<label asp-for="VehicleMakeId">Vehicle Make Id:</label>
			<input asp-for="VehicleMakeId" readonly />
		</div>
		<div class="form-group">
			<label asp-for="Name">Name:</label>
			<input asp-for="Name" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Abrv">Abrevation:</label>
			<input asp-for="Abrv" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<input type="submit" value="Add" class="btn" />
		</div>


	</form>
	<div>
		<a class="nav-link text-dark" asp-controller="VehicleMake" asp-action="Index">Back to list</a>
	</div>
</body>

Project/Project.MVC/Views/VehicleModel/Index.cshtml
@using Project.Service.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PageResult<VehicleModelDTO>
@{
	var vehicleModels = Model.Data;
	var query = Model.Query;
}
<div class="row">
	<h1>Vehicle Model</h1>

</div>
<div class="row">
	@using (Html.BeginForm("Index", "VehicleModel", FormMethod.Get))
	{
		@Html.TextBox("filter")<input type="submit" value="Search" />
	}
</div>
<div class="row">
	<table class="arrowes-table table-striped">
		<thead>
			<tr>
				<th>Id</th>
				<th>
							@{var sortOrderName = Equals(query.SortOrder, SortOrder.Ascending) ? SortOrder.Descending : SortOrder.Ascending;}
							@Html.ActionLink("Name", "Index", new { filter = query.Filter, page = query.Page, pageSize = query.PageSize, sortOrder = sortOrderName, sortBy = SortBy.Name }, new { @class = "text-dark" })
				</th>
				<th>
					@{
						var sortOrderAbrv = Equals(query.SortOrder, SortOrder.Ascending) ? SortOrder.Descending : SortOrder.Ascending;
					}
					@Html.ActionLink("Abrv", "Index", new { filter = query.Filter, page = query.Page, pageSize = query.PageSize, sortOrder = sortOrderAbrv, sortBy = SortBy.Abrv }, new { @class = "text-dark" })
				</th>
				<th></th>
				<th></th>
			</tr>
		</thead>


		<tbody>
			@foreach (var vehicleModel in vehicleModels)
			{
				<tr class="flex-row">
					<td>@vehicleModel.Id</td>
					<td>@vehicleModel.Name</td>
					<td>@vehicleModel.Abrv</td>

					<td>
						@Html.ActionLink("Edit", "UpdateVehicleModel", new { id=vehicleModel.Id},new {@class="text-dark"})
					</td>
					<td>
						@Html.ActionLink("Delete", "DeleteVehicleModel", new { id=vehicleModel.Id}, new {@class="text-dark"})
					</td>

				</tr>
			}
		</tbody>
	</table>
</div>
<div class="row">
	@{
		if (query.Page > 1)
		{
			<div class="col">
				<a>
					@Html.ActionLink($"{query.Page - 1}", "Index", new { filter=query.Filter, page = query.Page - 1, pageSize = query.PageSize, sort = query.SortOrder},new {@class="text-dark"})
				</a>
			</div>
		}
	}
	<div class="col">
		<a>
			@Html.ActionLink($"{query.Page}", "Index", new { filter=query.Filter, page = query.Page, pageSize = query.PageSize, sort = query.SortOrder})
		</a>
	</div>

	@{
		if (vehicleModels.Count() == query.PageSize)
		{
			<div class="col">
				<a>
					@Html.ActionLink($"{query.Page + 1}", "Index", new { filter=query.Filter, page = query.Page + 1, pageSize = query.PageSize, sort = query.SortOrder},new {@class="text-dark"})
				</a>
			</div>
		}

	}
</div>

Project/Project.MVC/Views/VehicleModel/UpdateVehicleModel.cshtml
@using Project.Service.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VehicleModelDTO
<head>
	<title>Update Vehicle Model</title>
</head>
<body>
	<form asp-action="UpdateVehicleModel">

		<div class="form-group">
			<input asp-for="Id" hidden />
		</div>
		<div class="form-group">
			<label asp-for="VehicleMakeId">Vehicle Make Id:</label>
			<input asp-for="VehicleMakeId" readonly />
		</div>
		<div class="form-group">
			<label asp-for="Name">Name:</label>
			<input asp-for="Name" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Abrv">Abrevation:</label>
			<input asp-for="Abrv" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<input type="submit" value="Add" class="btn" />
		</div>

	</form>
	<div>
		<a class="nav-link text-dark" asp-controller="VehicleModel" asp-action="Index">Back to list</a>
	</div>
</body>